# Remove '#' to select a file.

# gpt-engineer can only read selected files. Including irrelevant files will degrade performance, cost additional tokens and potentially overflow token limit.

[files]
"hugo.toml" = "selected"
# Makefile = "selected"
# "go.mod" = "selected"
# "go.sum" = "selected"
# "layouts/partials/custom-head.html" = "selected"
# "archetypes/default.md" = "selected"
# "posts/404.html" = "selected"
# "posts/index.html" = "selected"
# "posts/sitemap.xml" = "selected"
# "posts/index.xml" = "selected"
# "posts/js/bundle.js" = "selected"
# "posts/js/fontawesome6/all.min.js" = "selected"
# "posts/tags/index.html" = "selected"
# "posts/tags/index.xml" = "selected"
# "posts/categories/index.html" = "selected"
# "posts/categories/index.xml" = "selected"
# "posts/css/chroma.css" = "selected"
# "posts/css/theme.min.css" = "selected"
# "posts/css/chroma.min.css" = "selected"
# "posts/css/theme.css" = "selected"
# "themes/hugo-theme-techdoc/docker-compose.yml" = "selected"
# "themes/hugo-theme-techdoc/theme.toml" = "selected"
# "themes/hugo-theme-techdoc/package.json" = "selected"
# "themes/hugo-theme-techdoc/gulpfile.js" = "selected"
# "themes/hugo-theme-techdoc/README.md" = "selected"
# "themes/hugo-theme-techdoc/go.mod" = "selected"
# "themes/hugo-theme-techdoc/LICENSE.md" = "selected"
# "themes/hugo-theme-techdoc/webpack.config.js" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/config.toml" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/static/images/og-image.png" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/static/images/pexels-photo-196666.jpeg" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/_index.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/hello_world.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/about.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter1/1.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter1/_index.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter1/4.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter1/2.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter1/3.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/archives/hello_world.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/archives/hello_world1.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/archives/hello_world2.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter4/_index.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter4/chapter4-1/_index.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter4/chapter4-1/chapter4-1-1/_index.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter4/chapter4-1/chapter4-1-1/chapter4-1-1-1/_index.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter4/chapter4-1/chapter4-1-1/chapter4-1-1-1/chapter4-1-1-1-1/_index.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter4/chapter4-1/chapter4-1-1/chapter4-1-1-1/chapter4-1-1-1-1/chapter4-1-1-1-1-1/_index.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter4/chapter4-1/chapter4-1-1/chapter4-1-1-1/chapter4-1-1-1-1/chapter4-1-1-1-1-1/chapter4-1-1-1-1-1-1/_index.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/post/migrate-from-jekyll.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/post/hugoisforlovers.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/post/creating-a-new-theme.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/post/goisforlovers.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/entry/hello_world.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/entry/hello_world1.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/entry/hello_world2.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/getting-started/screenshot.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/getting-started/_index.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/getting-started/configuration.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/getting-started/installation.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter2/1.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter2/_index.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter2/4.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter2/5.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter2/2.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter2/3.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/posts/hello_world.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/blog/hello_world.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/blog/hello_world1.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/blog/hello_world2.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter3/1.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter3/_index.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter3/4.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter3/3.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter3/chapter3-2/1.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter3/chapter3-2/_index.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter3/chapter3-2/4.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter3/chapter3-2/2.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/chapter3/chapter3-2/3.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/sample/_index.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/sample/build-in-shortcodes.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/sample/custom-shortcodes.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/sample/search-shortcode.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/sample/table-of-contents.md" = "selected"
# "themes/hugo-theme-techdoc/exampleSite/content/sample/markdown-syntax.md" = "selected"
# "themes/hugo-theme-techdoc/static/js/bundle.js" = "selected"
# "themes/hugo-theme-techdoc/static/js/fontawesome6/all.min.js" = "selected"
# "themes/hugo-theme-techdoc/static/css/chroma.css" = "selected"
# "themes/hugo-theme-techdoc/static/css/theme.min.css" = "selected"
# "themes/hugo-theme-techdoc/static/css/chroma.min.css" = "selected"
# "themes/hugo-theme-techdoc/static/css/theme.css" = "selected"
# "themes/hugo-theme-techdoc/layouts/404.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/index.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/edit-page.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/head.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/global-menu.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/table-of-contents.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/site-header.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/content-footer.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/pagination.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/sidebar.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/footer.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/sidebar-footer.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/last-updated.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/edit-meta.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/custom-css.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/search.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/prepend-body.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/notification.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/powered.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/custom-head.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/menu/open-menu.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/menu/slide-menu.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/meta/chroma.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/meta/google-site-verification.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/meta/google-analytics-async.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/meta/simple-analytics.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/partials/meta/tag-manager.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/shortcodes/panel.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/shortcodes/code.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/shortcodes/search.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/shortcodes/button.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/_default/list.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/_default/list.algolia.json" = "selected"
# "themes/hugo-theme-techdoc/layouts/_default/single.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/_default/baseof.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/_default/_markup/render-codeblock-mermaid.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/posts/list.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/posts/single.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/blog/list.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/blog/single.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/blog/li.html" = "selected"
# "themes/hugo-theme-techdoc/layouts/blog/summary.html" = "selected"
# "themes/hugo-theme-techdoc/images/screenshot-slide-menu.gif" = "selected"
# "themes/hugo-theme-techdoc/images/screenshot-edit-link.png" = "selected"
# "themes/hugo-theme-techdoc/images/screenshot-open-menu.png" = "selected"
# "themes/hugo-theme-techdoc/images/screenshot.png" = "selected"
# "themes/hugo-theme-techdoc/images/screenshot-theme-color.png" = "selected"
# "themes/hugo-theme-techdoc/images/tn.png" = "selected"
# "themes/hugo-theme-techdoc/archetypes/default.md" = "selected"
# "themes/hugo-theme-techdoc/src/scss/_component.scss" = "selected"
# "themes/hugo-theme-techdoc/src/scss/_variable.scss" = "selected"
# "themes/hugo-theme-techdoc/src/scss/_structure.scss" = "selected"
# "themes/hugo-theme-techdoc/src/scss/theme.scss" = "selected"
# "themes/hugo-theme-techdoc/src/scss/chroma.scss" = "selected"
# "themes/hugo-theme-techdoc/src/scss/_project.scss" = "selected"
# "themes/hugo-theme-techdoc/src/scss/function/_calc-stack.scss" = "selected"
# "themes/hugo-theme-techdoc/src/scss/function/_strip-unit.scss" = "selected"
# "themes/hugo-theme-techdoc/src/scss/function/_contrast-color.scss" = "selected"
# "themes/hugo-theme-techdoc/src/scss/function/_calc-font-size.scss" = "selected"
# "themes/hugo-theme-techdoc/src/scss/foundation/_reset.scss" = "selected"
# "themes/hugo-theme-techdoc/src/scss/foundation/_element.scss" = "selected"
# "themes/hugo-theme-techdoc/src/scss/foundation/_normalize.scss" = "selected"
# "themes/hugo-theme-techdoc/src/scss/foundation/_stack.scss" = "selected"
# "themes/hugo-theme-techdoc/src/scss/foundation/_index.scss" = "selected"
# "themes/hugo-theme-techdoc/src/js/keydown-nav.js" = "selected"
# "themes/hugo-theme-techdoc/src/js/headerlink.js" = "selected"
# "themes/hugo-theme-techdoc/src/js/code.js" = "selected"
# "themes/hugo-theme-techdoc/src/js/main.js" = "selected"
# "themes/hugo-theme-techdoc/src/js/sidebar-menu.js" = "selected"
# "themes/hugo-theme-techdoc/src/js/jquery.backtothetop/jquery.backtothetop.js" = "selected"
# "themes/hugo-theme-techdoc/src/js/jquery.backtothetop/jquery.backtothetop.min.js" = "selected"
# 
