# Remove '#' to select a file.

# gpt-engineer can only read selected files. Including irrelevant files will degrade performance, cost additional tokens and potentially overflow token limit.

[files]
# "en/life-hacks/Internet-From-Shared-Scooter.md" = "selected"
# "en/life-hacks/too-good-to-go.md" = "selected"
# "en/life-hacks/get-crow-workers.md" = "selected"
# "en/resources/_gen/assets/scss/localhost/styles/app.scss_8c70af5d938c27a6cb0d5290a81b6bb7.content" = "selected"
# "en/resources/_gen/assets/scss/localhost/styles/app.scss_8c70af5d938c27a6cb0d5290a81b6bb7.json" = "selected"
# "en/resources/_gen/assets/scss/localhost/scss/main.scss_de1a7f5f1c8c46959803c429bb697ff0.json" = "selected"
# "en/resources/_gen/assets/scss/localhost/scss/main.scss_de1a7f5f1c8c46959803c429bb697ff0.content" = "selected"
# "en/resources/_gen/assets/scss/css/base.scss_997d102b57f87ae4d0d67e2b1aa7754c.content" = "selected"
# "en/resources/_gen/assets/scss/css/base.scss_997d102b57f87ae4d0d67e2b1aa7754c.json" = "selected"
# "en/resources/_gen/assets/css/localhost/ananke/css/main.css_bb5467e0521bbea6b1e66429f6ec028e.content" = "selected"
# "en/resources/_gen/assets/css/localhost/ananke/css/main.css_bb5467e0521bbea6b1e66429f6ec028e.json" = "selected"
# "en/resources/_gen/assets/css/ananke/css/main.css_bb5467e0521bbea6b1e66429f6ec028e.content" = "selected"
 "en/Rewards/Walking-Money.md" = "selected"
# "en/Rewards/Trashback-Rewards.md" = "selected"
# "en/money/La-Cuponera.md" = "selected"
# "en/money/get-paid-for-housekeeping.md" = "selected"
# "en/money/CodeArena.md" = "selected"
# "en/money/learn-and-earn-crypto.md" = "selected"
# "en/money/stacking-crypto.md" = "selected"
# "en/money/Google-Opinion-Rewards.md" = "selected"
# "en/money/how-to-make-money-solving-git-issues.md" = "selected"
# "en/money/how-to-make-money-trashback.md" = "selected"
# "en/money/Sweatcoin-Walking-Rewards.md" = "selected"
# "en/money/how-to-make-money-google-rewards.md" = "selected"
# "en/money/Bat-Brave-Rewards.md" = "selected"
