baseURL = 'https://digitramp.org/'
languageCode = 'en-us'
title = "Digitramp"
metaDataFormat = "yaml"
theme = 'hello-4s3ti'
defaultContentLanguage = "en"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = false
googleAnalytics = "G-FVDM84RPVX"

paginate = 10
disableReadOtherPosts = false
enableSharingButtons = true

[languages]
  [languages.en]
    contentDir = '../content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Digitramp'
    weight = 2
    [languages.en.params]
      subtitle = 'Nomad life 3.0: Reference, Tutorials, and Explanations'
  [languages.fr]
    contentDir = '../content/fr'
    disabled = false
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'Français'
    title = 'Digitramp'
    weight = 3
    [languages.fr.params]
      subtitle = 'La vie nomade 3.0 : Référence, Tutoriels et Explications'
  [languages.es]
    contentDir = '../content/es'
    disabled = false
    languageCode = 'es-ES'
    languageDirection = 'ltr'
    languageName = 'Español'
    title = 'Digitramp'
    weight = 4
    [languages.es.params]
      subtitle = 'Vida nómada 3.0: Referencia, Tutoriales y Explicaciones'
  [languages.ca]
    contentDir = '../content/ca'
    disabled = false
    languageCode = 'ca-ES'
    languageDirection = 'ltr'
    languageName = 'Català'
    title = 'Digitramp'
    weight = 5
    [languages.ca.params]
      subtitle = 'Vida nòmada 3.0: Referència, Tutoriales i Explicacions'
  [languages.eu]
    contentDir = '../content/eu'
    disabled = false
    languageCode = 'eu-ES'
    languageDirection = 'ltr'
    languageName = 'Euskera'
    title = 'Digitramp'
    weight = 6
    [languages.eu.params]
      subtitle = 'Nomad bizitza 3.0: Erreferentzia, Tutorialak eta Azalpenak'


[params]
    title = "Digitramp's Notes"
    description = "Parallel World"

    github_repository = "https://github.com/ack-ninja/digitramp.org"
    #version = "0.0.1-dev"

    github_doc_repository = "https://github.com/Ack-Ninja/digitramp.org"
    github_doc_repository_path = ""
    github_doc_repository_branch = "main"

    custom_font_color = ""
    custom_background_color = ""

    menu_style = "open-menu"

    dateformat = "" # 2 Jan 2006

    menu_exclusion = ["archives"]

    algolia_search_enable = false

    ordersectionsby = 'weight'

[menu]
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    identifier = "home"
    pre = "<i class='fa fa-heart'></i>&nbsp;"

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe = true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = true
