baseURL = 'https://digitramp.org/'
languageCode = 'en-us'
title = "Digitramp"
metaDataFormat = "yaml"
theme = 'hugo-theme-techdoc'
defaultContentLanguage = "en"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = false
googleAnalytics = "G-FVDM84RPVX"

[languages]
  [languages.de]
    contentDir = 'content/de'
    disabled = false
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    title = 'Projekt Dokumentation'
    weight = 1
    [languages.de.params]
      subtitle = 'Referenz, Tutorials und Erklärungen'
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Project Documentation'
    weight = 2
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'

[params]
    title = "Digitramp's Notes"
    #images = ["images/og-image.png"] # static/images
    description = "Parallel World"

    github_repository = "https://github.com/ack-ninja/digitramp.org"
    #version = "0.0.1-dev"

    github_doc_repository = "https://github.com/Ack-Ninja/digitramp.org"
    github_doc_repository_path = ""
    github_doc_repository_branch = "main"

    custom_font_color = ""
    custom_background_color = ""

    menu_style = "open-menu"

    dateformat = "" # 2 Jan 2006

    menu_exclusion = ["archives"]

    algolia_search_enable = false

    ordersectionsby = 'weight'

[menu]
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    identifier = "home"
    pre = "<i class='fa fa-heart'></i>&nbsp;"

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe = true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = true

[outputs]
    home = ["HTML", "RSS"]

[permalinks]
    [permalinks.page]
        posts = '/:slug/'
        wikis = '/:slug/'
    [permalinks.section]
        posts = '/posts/'
        wikis = '/wikis/'

#[module]
#    [[module.imports]]
#        path = "github.com/thingsym/hugo-theme-techdoc"
