# Remove '#' to select a file.

# gpt-engineer can only read selected files. Including irrelevant files will degrade performance, cost additional tokens and potentially overflow token limit.

[files]
 "config.yml" = "selected"
# LICENSE = "selected"
# "theme.toml" = "selected"
# "README.md" = "selected"
# "go.mod" = "selected"
# "netlify.toml" = "selected"
# "assets/js/license.js" = "selected"
# "assets/js/fastsearch.js" = "selected"
# "assets/js/fuse.basic.min.js" = "selected"
# "assets/css/extended/blank.css" = "selected"
# "assets/css/core/reset.css" = "selected"
# "assets/css/core/theme-vars.css" = "selected"
# "assets/css/core/zmedia.css" = "selected"
# "assets/css/core/license.css" = "selected"
# "assets/css/common/terms.css" = "selected"
# "assets/css/common/404.css" = "selected"
# "assets/css/common/archive.css" = "selected"
# "assets/css/common/post-entry.css" = "selected"
# "assets/css/common/header.css" = "selected"
# "assets/css/common/main.css" = "selected"
# "assets/css/common/search.css" = "selected"
# "assets/css/common/profile-mode.css" = "selected"
# "assets/css/common/post-single.css" = "selected"
# "assets/css/common/footer.css" = "selected"
# "assets/css/includes/scroll-bar.css" = "selected"
# "assets/css/includes/chroma-styles.css" = "selected"
# "assets/css/includes/chroma-mod.css" = "selected"
# "public/404.html" = "selected"
# "public/index.html" = "selected"
# "public/sitemap.xml" = "selected"
# "public/index.xml" = "selected"
# "public/robots.txt" = "selected"
# "public/index.json" = "selected"
# "public/fr/404.html" = "selected"
# "public/fr/index.html" = "selected"
# "public/fr/sitemap.xml" = "selected"
# "public/fr/index.xml" = "selected"
# "public/fr/index.json" = "selected"
# "public/fr/frcategories/index.html" = "selected"
# "public/fr/frcategories/index.xml" = "selected"
# "public/fr/frseries/index.html" = "selected"
# "public/fr/frseries/index.xml" = "selected"
# "public/fr/frtags/index.html" = "selected"
# "public/fr/frtags/index.xml" = "selected"
# "public/assets/css/stylesheet.b609c58d5c11bb90b1a54e04005d74ad1ddf22165eb79f5533967e57df9c3b50.css" = "selected"
# "public/en/index.html" = "selected"
# "public/en/sitemap.xml" = "selected"
# "public/en/resources/_gen/assets/scss/localhost/styles/app.scss_8c70af5d938c27a6cb0d5290a81b6bb7.content" = "selected"
# "public/en/resources/_gen/assets/scss/localhost/styles/app.scss_8c70af5d938c27a6cb0d5290a81b6bb7.json" = "selected"
# "public/en/resources/_gen/assets/scss/localhost/scss/main.scss_de1a7f5f1c8c46959803c429bb697ff0.json" = "selected"
# "public/en/resources/_gen/assets/scss/localhost/scss/main.scss_de1a7f5f1c8c46959803c429bb697ff0.content" = "selected"
# "public/en/resources/_gen/assets/scss/css/base.scss_997d102b57f87ae4d0d67e2b1aa7754c.content" = "selected"
# "public/en/resources/_gen/assets/scss/css/base.scss_997d102b57f87ae4d0d67e2b1aa7754c.json" = "selected"
# "public/en/resources/_gen/assets/css/localhost/ananke/css/main.css_bb5467e0521bbea6b1e66429f6ec028e.content" = "selected"
# "public/en/resources/_gen/assets/css/localhost/ananke/css/main.css_bb5467e0521bbea6b1e66429f6ec028e.json" = "selected"
# "public/en/resources/_gen/assets/css/ananke/css/main.css_bb5467e0521bbea6b1e66429f6ec028e.content" = "selected"
# "public/series/index.html" = "selected"
# "public/series/index.xml" = "selected"
# "public/eu/index.html" = "selected"
# "public/tags/index.html" = "selected"
# "public/tags/index.xml" = "selected"
# "public/fa/404.html" = "selected"
# "public/fa/index.html" = "selected"
# "public/fa/sitemap.xml" = "selected"
# "public/fa/index.xml" = "selected"
# "public/fa/index.json" = "selected"
# "public/fa/facategories/index.html" = "selected"
# "public/fa/facategories/index.xml" = "selected"
# "public/fa/fatags/index.html" = "selected"
# "public/fa/fatags/index.xml" = "selected"
# "public/fa/faseries/index.html" = "selected"
# "public/fa/faseries/index.xml" = "selected"
# "public/fa/page/1/index.html" = "selected"
# "public/categories/index.html" = "selected"
# "public/categories/index.xml" = "selected"
# "public/es/index.html" = "selected"
# "public/ca/index.html" = "selected"
# "public/page/1/index.html" = "selected"
# "i18n/de.yaml" = "selected"
# "i18n/vi.yaml" = "selected"
# "i18n/ar.yaml" = "selected"
# "i18n/be.yaml" = "selected"
# "i18n/ku.yaml" = "selected"
# "i18n/sw.yaml" = "selected"
# "i18n/ms.yaml" = "selected"
# "i18n/bg.yaml" = "selected"
# "i18n/uk.yaml" = "selected"
# "i18n/id.yaml" = "selected"
# "i18n/pa.yaml" = "selected"
# "i18n/fr.yaml" = "selected"
# "i18n/cs.yaml" = "selected"
# "i18n/uz.yaml" = "selected"
# "i18n/zh-tw.yaml" = "selected"
# "i18n/no.yaml" = "selected"
# "i18n/hi.yaml" = "selected"
# "i18n/ja.yaml" = "selected"
# "i18n/es.yaml" = "selected"
# "i18n/it.yaml" = "selected"
# "i18n/sk.yaml" = "selected"
# "i18n/hu.yaml" = "selected"
# "i18n/zh.yaml" = "selected"
# "i18n/fa.yaml" = "selected"
# "i18n/he.yaml" = "selected"
# "i18n/ru.yaml" = "selected"
# "i18n/nl.yaml" = "selected"
# "i18n/ca.yaml" = "selected"
# "i18n/mn.yaml" = "selected"
# "i18n/ko.yaml" = "selected"
# "i18n/pl.yaml" = "selected"
# "i18n/el.yaml" = "selected"
# "i18n/bn.yaml" = "selected"
# "i18n/ro.yaml" = "selected"
# "i18n/pt.yaml" = "selected"
# "i18n/hr.yaml" = "selected"
# "i18n/eo.yaml" = "selected"
# "i18n/sv.yaml" = "selected"
# "i18n/tr.yaml" = "selected"
# "i18n/ckb.yaml" = "selected"
# "i18n/da.yaml" = "selected"
# "i18n/en.yaml" = "selected"
# "i18n/pnb.yaml" = "selected"
# "i18n/th.yaml" = "selected"
# "layouts/404.html" = "selected"
# "layouts/robots.txt" = "selected"
# "layouts/partials/svg.html" = "selected"
# "layouts/partials/cover.html" = "selected"
# "layouts/partials/index_profile.html" = "selected"
# "layouts/partials/head.html" = "selected"
# "layouts/partials/post_canonical.html" = "selected"
# "layouts/partials/post_meta.html" = "selected"
# "layouts/partials/anchored_headings.html" = "selected"
# "layouts/partials/social_icons.html" = "selected"
# "layouts/partials/translation_list.html" = "selected"
# "layouts/partials/author.html" = "selected"
# "layouts/partials/comments.html" = "selected"
# "layouts/partials/extend_footer.html" = "selected"
# "layouts/partials/extend_head.html" = "selected"
# "layouts/partials/home_info.html" = "selected"
# "layouts/partials/post_nav_links.html" = "selected"
# "layouts/partials/footer.html" = "selected"
# "layouts/partials/header.html" = "selected"
# "layouts/partials/toc.html" = "selected"
# "layouts/partials/breadcrumbs.html" = "selected"
# "layouts/partials/share_icons.html" = "selected"
# "layouts/partials/edit_post.html" = "selected"
# "layouts/partials/templates/twitter_cards.html" = "selected"
# "layouts/partials/templates/schema_json.html" = "selected"
# "layouts/partials/templates/opengraph.html" = "selected"
# "layouts/partials/templates/_funcs/get-page-images.html" = "selected"
# "layouts/shortcodes/inTextImg.html" = "selected"
# "layouts/shortcodes/ltr.html" = "selected"
# "layouts/shortcodes/rawhtml.html" = "selected"
# "layouts/shortcodes/rtl.html" = "selected"
# "layouts/shortcodes/figure.html" = "selected"
# "layouts/shortcodes/collapse.html" = "selected"
# "layouts/_default/archives.html" = "selected"
# "layouts/_default/list.html" = "selected"
# "layouts/_default/rss.xml" = "selected"
# "layouts/_default/single.html" = "selected"
# "layouts/_default/terms.html" = "selected"
# "layouts/_default/search.html" = "selected"
# "layouts/_default/baseof.html" = "selected"
# "layouts/_default/index.json" = "selected"
# "layouts/_default/_markup/render-image.html" = "selected"
# "content/fr/index.md" = "selected"
# "content/fr/Rewards/Walking-Money.md" = "selected"
# "content/en/index.md" = "selected"
# "content/en/life-hacks/Internet-From-Shared-Scooter.md" = "selected"
# "content/en/life-hacks/too-good-to-go.md" = "selected"
# "content/en/life-hacks/get-crow-workers.md" = "selected"
# "content/en/resources/_gen/assets/scss/localhost/styles/app.scss_8c70af5d938c27a6cb0d5290a81b6bb7.content" = "selected"
# "content/en/resources/_gen/assets/scss/localhost/styles/app.scss_8c70af5d938c27a6cb0d5290a81b6bb7.json" = "selected"
# "content/en/resources/_gen/assets/scss/localhost/scss/main.scss_de1a7f5f1c8c46959803c429bb697ff0.json" = "selected"
# "content/en/resources/_gen/assets/scss/localhost/scss/main.scss_de1a7f5f1c8c46959803c429bb697ff0.content" = "selected"
# "content/en/resources/_gen/assets/scss/css/base.scss_997d102b57f87ae4d0d67e2b1aa7754c.content" = "selected"
# "content/en/resources/_gen/assets/scss/css/base.scss_997d102b57f87ae4d0d67e2b1aa7754c.json" = "selected"
# "content/en/resources/_gen/assets/css/localhost/ananke/css/main.css_bb5467e0521bbea6b1e66429f6ec028e.content" = "selected"
# "content/en/resources/_gen/assets/css/localhost/ananke/css/main.css_bb5467e0521bbea6b1e66429f6ec028e.json" = "selected"
# "content/en/resources/_gen/assets/css/ananke/css/main.css_bb5467e0521bbea6b1e66429f6ec028e.content" = "selected"
# "content/en/Rewards/Walking-Money.md" = "selected"
# "content/en/Rewards/Trashback-Rewards.md" = "selected"
# "content/en/money/La-Cuponera.md" = "selected"
# "content/en/money/get-paid-for-housekeeping.md" = "selected"
# "content/en/money/CodeArena.md" = "selected"
# "content/en/money/learn-and-earn-crypto.md" = "selected"
# "content/en/money/stacking-crypto.md" = "selected"
# "content/en/money/Google-Opinion-Rewards.md" = "selected"
# "content/en/money/how-to-make-money-solving-git-issues.md" = "selected"
# "content/en/money/how-to-make-money-trashback.md" = "selected"
# "content/en/money/Sweatcoin-Walking-Rewards.md" = "selected"
# "content/en/money/how-to-make-money-google-rewards.md" = "selected"
# "content/en/money/Bat-Brave-Rewards.md" = "selected"
# "content/eu/index.md" = "selected"
# "content/eu/Rewards/Walking-Money.md" = "selected"
# "content/es/index.md" = "selected"
# "content/es/Rewards/Walking-Money.md" = "selected"
# "content/ca/index.md" = "selected"
# "content/ca/Rewards/Walking-Money.md" = "selected"
# "images/screenshot.png" = "selected"
# "images/tn.png" = "selected"
# "themes/hugo-PaperMod/LICENSE" = "selected"
# "themes/hugo-PaperMod/theme.toml" = "selected"
# "themes/hugo-PaperMod/README.md" = "selected"
# "themes/hugo-PaperMod/go.mod" = "selected"
# "themes/hugo-PaperMod/assets/js/license.js" = "selected"
# "themes/hugo-PaperMod/assets/js/fastsearch.js" = "selected"
# "themes/hugo-PaperMod/assets/js/fuse.basic.min.js" = "selected"
# "themes/hugo-PaperMod/assets/css/extended/blank.css" = "selected"
# "themes/hugo-PaperMod/assets/css/core/reset.css" = "selected"
# "themes/hugo-PaperMod/assets/css/core/theme-vars.css" = "selected"
# "themes/hugo-PaperMod/assets/css/core/zmedia.css" = "selected"
# "themes/hugo-PaperMod/assets/css/core/license.css" = "selected"
# "themes/hugo-PaperMod/assets/css/common/terms.css" = "selected"
# "themes/hugo-PaperMod/assets/css/common/404.css" = "selected"
# "themes/hugo-PaperMod/assets/css/common/archive.css" = "selected"
# "themes/hugo-PaperMod/assets/css/common/post-entry.css" = "selected"
# "themes/hugo-PaperMod/assets/css/common/header.css" = "selected"
# "themes/hugo-PaperMod/assets/css/common/main.css" = "selected"
# "themes/hugo-PaperMod/assets/css/common/search.css" = "selected"
# "themes/hugo-PaperMod/assets/css/common/profile-mode.css" = "selected"
# "themes/hugo-PaperMod/assets/css/common/post-single.css" = "selected"
# "themes/hugo-PaperMod/assets/css/common/footer.css" = "selected"
# "themes/hugo-PaperMod/assets/css/includes/scroll-bar.css" = "selected"
# "themes/hugo-PaperMod/assets/css/includes/chroma-styles.css" = "selected"
# "themes/hugo-PaperMod/assets/css/includes/chroma-mod.css" = "selected"
# "themes/hugo-PaperMod/i18n/de.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/vi.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/ar.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/be.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/ku.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/sw.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/ms.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/bg.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/uk.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/id.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/pa.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/fr.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/cs.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/uz.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/zh-tw.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/no.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/hi.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/ja.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/es.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/it.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/sk.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/hu.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/zh.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/fa.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/he.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/ru.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/nl.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/ca.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/mn.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/ko.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/pl.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/el.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/bn.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/ro.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/pt.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/hr.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/eo.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/sv.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/tr.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/ckb.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/da.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/en.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/pnb.yaml" = "selected"
# "themes/hugo-PaperMod/i18n/th.yaml" = "selected"
# "themes/hugo-PaperMod/layouts/404.html" = "selected"
# "themes/hugo-PaperMod/layouts/robots.txt" = "selected"
# "themes/hugo-PaperMod/layouts/partials/svg.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/cover.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/index_profile.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/head.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/post_canonical.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/post_meta.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/anchored_headings.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/social_icons.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/translation_list.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/author.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/comments.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/extend_footer.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/extend_head.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/home_info.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/post_nav_links.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/footer.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/header.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/toc.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/breadcrumbs.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/share_icons.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/edit_post.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/templates/twitter_cards.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/templates/schema_json.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/templates/opengraph.html" = "selected"
# "themes/hugo-PaperMod/layouts/partials/templates/_funcs/get-page-images.html" = "selected"
# "themes/hugo-PaperMod/layouts/shortcodes/inTextImg.html" = "selected"
# "themes/hugo-PaperMod/layouts/shortcodes/ltr.html" = "selected"
# "themes/hugo-PaperMod/layouts/shortcodes/rawhtml.html" = "selected"
# "themes/hugo-PaperMod/layouts/shortcodes/rtl.html" = "selected"
# "themes/hugo-PaperMod/layouts/shortcodes/figure.html" = "selected"
# "themes/hugo-PaperMod/layouts/shortcodes/collapse.html" = "selected"
# "themes/hugo-PaperMod/layouts/_default/archives.html" = "selected"
# "themes/hugo-PaperMod/layouts/_default/list.html" = "selected"
# "themes/hugo-PaperMod/layouts/_default/rss.xml" = "selected"
# "themes/hugo-PaperMod/layouts/_default/single.html" = "selected"
# "themes/hugo-PaperMod/layouts/_default/terms.html" = "selected"
# "themes/hugo-PaperMod/layouts/_default/search.html" = "selected"
# "themes/hugo-PaperMod/layouts/_default/baseof.html" = "selected"
# "themes/hugo-PaperMod/layouts/_default/index.json" = "selected"
# "themes/hugo-PaperMod/layouts/_default/_markup/render-image.html" = "selected"
# "themes/hugo-PaperMod/images/screenshot.png" = "selected"
# "themes/hugo-PaperMod/images/tn.png" = "selected"
