# Remove '#' to select a file.

# gpt-engineer can only read selected files. Including irrelevant files will degrade performance, cost additional tokens and potentially overflow token limit.

[files]
# LICENSE = "selected"
# "_index.md" = "selected"
# "README.md" = "selected"
# "netlify.toml" = "selected"
# "life-hacks/Internet-From-Shared-Scooter.md" = "selected"
# "life-hacks/too-good-to-go.md" = "selected"
# "life-hacks/get-crow-workers.md" = "selected"
# "static/android-chrome-192x192.png" = "selected"
# "static/apple-touch-icon.png" = "selected"
# "static/android-chrome-512x512.png" = "selected"
# "static/site.webmanifest" = "selected"
# "resources/_gen/assets/scss/localhost/styles/app.scss_8c70af5d938c27a6cb0d5290a81b6bb7.content" = "selected"
# "resources/_gen/assets/scss/localhost/styles/app.scss_8c70af5d938c27a6cb0d5290a81b6bb7.json" = "selected"
# "resources/_gen/assets/scss/localhost/scss/main.scss_de1a7f5f1c8c46959803c429bb697ff0.json" = "selected"
# "resources/_gen/assets/scss/localhost/scss/main.scss_de1a7f5f1c8c46959803c429bb697ff0.content" = "selected"
# "resources/_gen/assets/scss/css/base.scss_997d102b57f87ae4d0d67e2b1aa7754c.content" = "selected"
# "resources/_gen/assets/scss/css/base.scss_997d102b57f87ae4d0d67e2b1aa7754c.json" = "selected"
# "resources/_gen/assets/css/localhost/ananke/css/main.css_bb5467e0521bbea6b1e66429f6ec028e.content" = "selected"
# "resources/_gen/assets/css/localhost/ananke/css/main.css_bb5467e0521bbea6b1e66429f6ec028e.json" = "selected"
# "resources/_gen/assets/css/ananke/css/main.css_bb5467e0521bbea6b1e66429f6ec028e.content" = "selected"
# "Rewards/Walking-Money.md" = "selected"
# "Rewards/Trashback-Rewards.md" = "selected"
# "money/La-Cuponera.md" = "selected"
# "money/get-paid-for-housekeeping.md" = "selected"
# "money/CodeArena.md" = "selected"
# "money/learn-and-earn-crypto.md" = "selected"
# "money/stacking-crypto.md" = "selected"
# "money/Google-Opinion-Rewards.md" = "selected"
# "money/how-to-make-money-solving-git-issues.md" = "selected"
# "money/how-to-make-money-trashback.md" = "selected"
# "money/Sweatcoin-Walking-Rewards.md" = "selected"
# "money/how-to-make-money-google-rewards.md" = "selected"
# "money/Bat-Brave-Rewards.md" = "selected"
